server:
  port: 8080
  servlet:
    context-path: /manage-server
#应用名称
spring:
  application:
    name: manage-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.106.147.32:3306/shepherd?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 980583990Yp.
